eureka:
  instance:
    preferIpAddress: false
    hostname: document-service
    nonSecurePort: 8091

  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka

spring:
  datasource:
    driverClassName: org.postgresql.Driver
