server:
  port: 8761

eureka:
  instance:
    preferIpAddress: false
    hostname: eureka-server
    nonSecurePort: 8761

  client:
    registerWithEureka: false
    fetchRegistry: false

  server:
    enableSelfPreservation: true

management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      show-details: always
