server:
  port: 8092

spring:
  application:
    name: storage-service

  profiles:
    active: docker

eureka:
  instance:
    preferIpAddress: false
    hostname: storage-service
    nonSecurePort: 8092

  client:
    registerWithEureka: true
    fetchRegistry: true


