eureka:
  instance:
    preferIpAddress: false
    hostname: storage-service
    nonSecurePort: 8092

  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
